### ISSUE TITLE
내꺼 왜 퍼가냐

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#1]
https://github.com/randombox1234

@cryptozeny

**Comment by cryptozeny** [comment]
너가 저번처럼 폭파하고 먹튀할까봐 미리 박제해논건데?

**Comment by cryptozeny** [comment]
사기꾼아

**Comment by cryptozeny** [comment]
for english users, he is well known scammer, bitcoin platinum (aka wjcloud) and ethereum progpow (aka naikmyong). at last time he deleted all of his repo (account also) and ran out. i am archivig all of his history to report to police.

**Comment by streetcrypto7** [comment]
ㅇㅇ 욕한거 깃헙 신고 간드아 https://help.github.com/en/github/building-a-strong-community/reporting-abuse-or-spam#reporting-a-user 누구 신상인지 모르겠지만 doxxing 으로 깃헙 계정 날라갈꺼다 ㅅㄱ

**Comment by cryptozeny** [comment]
doxxing 으로 신고하려면 저 사기친 내용이 본인이 맞다는걸 본인이 증명한건데?

**Comment by streetcrypto7** [comment]
You couldn't expose anyone's home address or workplace even it is someone you don't like it :joy: , and I am 32 years old developer not a someone like you. Bye.

**Comment by cryptozeny** [comment]
doxxing means you confirmed that, you are the scammer of bitcoin platinum and ethereum progpow. thanks for confirming!

**Comment by streetcrypto7** [comment]
No I am not, and someone made a report of you are him https://bitcointalk.org/index.php?topic=5177722.msg52232488#msg52232488

**Comment by streetcrypto7** [comment]
Please, don't doxx no one like you did it from discord ( you was doxxing @minkcrypto before )

**Comment by streetcrypto7** [comment]
https://help.github.com/en/github/site-policy/github-community-guidelines Reference for you 

```
Doxxing and invasion of privacy - Don't post other people's personal information, such as phone numbers, private email addresses, physical addresses, credit card numbers, Social Security/National Identity numbers, or passwords. Depending on the context, such as in the case of intimidation or harassment, we may consider other information, such as photos or videos that were taken or distributed without the subject's consent, to be an invasion of privacy, especially when such material presents a safety risk to the subject.
```

```
Hate speech and discrimination - While it is not forbidden to broach topics such as age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation, we do not tolerate speech that attacks a person or group of people on the basis of who they are. Just realize that when approached in an aggressive or insulting manner, these (and other) sensitive topics can make others feel unwelcome, or perhaps even unsafe. While there's always the potential for misunderstandings, we expect our community members to remain respectful and civil when discussing sensitive topics.
```

Good luck @cryptozeny

**Comment by cryptozeny** [comment]
깃허브는 절대 소스코드 안지우는거 알지? 쓸데없는일 하지마라

**Comment by streetcrypto7** [comment]
Yeah, but it will delete your account if you doxx, thanks 👍

**Comment by streetcrypto7** [comment]
Are you afraid of consequences for what you did?

**Comment by cryptozeny** [comment]
you are confirming that you are the scammer. thank you.

**Comment by cryptozeny** [comment]
경찰서에서 보자 이미 신고했다.

**Comment by streetcrypto7** [comment]
You are anonymous individual who enjoys hate speech and doxxing anyone's personal profile, now we have penalties to punish your behavioral

**Comment by streetcrypto7** [comment]
Enjoy your account being deleted for doing illegal things violating the rules.

**Comment by cryptozeny** [comment]
깃허브보단 경찰이랑 그사람이 더 먼저갈것같은데

**Comment by streetcrypto7** [comment]
Why not? I did nothing illegal like you 😂, you have the wrong opponent. I am 33 years old and you?

**Comment by cryptozeny** [comment]
경찰면담 준비해

**Comment by streetcrypto7** [comment]
You are the one who enjoys hate speech and doing antisocial things like sharing child abusive contents on your discord, could you do it here also?

**Comment by cryptozeny** [comment]
수고가많다 ㅋㅋ

**Comment by streetcrypto7** [comment]
Are you admitting to share those contents on github and discord?

**Comment by cryptozeny** [comment]
i am sharing this post with police

**Comment by streetcrypto7** [comment]
Yeah I am sharing your illegal, anti-social hate speech and doxxing with github safety team. Good luck.

**Comment by streetcrypto7** [comment]
Do you read bible @cryptozeny ?

**Comment by cryptozeny** [comment]
경찰이 더 먼저갈거같다. 그동안 수고했다.

**Comment by streetcrypto7** [comment]
There's a passage that I got memorized, seems appropiate for this situation: Ezekiel 25,17. "The path of the righteous man is beset of all sides by the iniquities of the selfish and the tyranny of evil me. Blessed is he who, in the name of the charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy my brothers. And you will know my name is the Lord when I lay my vengeance upon thee.

**Comment by streetcrypto7** [comment]
It is the end for you @cryptozeny , I am the shepherds of the developer community, I've contributed open source better than you are ( more than 10 years ).
