### ISSUE TITLE
이 패륜아 새끼야

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#11]
본인이 생각했을때 에이즈 걸린거 같으면 가족도 만나지 말고 셀프격리나 해라 이 똥꼬충 새끼야

**Comment by streetcrypto7** [comment]
자꾸 경찰 사칭하는데 경찰도 느같은 더러운 새끼는 감염될까봐 안 만나준다 안 만나고 테이져건 쏴서 병원 보내지

**Comment by cryptozeny** [comment]
욕설로 추가 신고했다 ㅅㄱ
