### ISSUE TITLE
너 에이즈 보균자라고 동네 방네 다 떠들고 다닐꺼다

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#13]
차갤에도 올리고 알갤에도 올리고 비트코인톡 디스코드 텔레그램 다 올릴꺼다

느그 코인 홀더들도 이건 아니다 싶어서 다 떨어져 나가겠지 ㅋㅋㅋㅋ

넌 이제 뒤졌어 내가 너 가는곳마다 에이즈 보균자라고 소문내고 다닐꺼임

**Comment by cryptozeny** [comment]
ㅁㅊ 스팸 그만
