### ISSUE TITLE
에이즈 보균자 새끼 놀리는거 꿀잼이노 ㅋㅋㅋ

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#14]
느 같은 새끼들 퀴어 축제 가면 많다

담에 한번 가서 느 같은 새끼들 주먹으로 패면서 인생의 즐거움을 찾아야겠다

느도 내가 너 보건소에 에이즈 보균자라고 신고하면 경찰이 에이즈 예방관리법에 따라 너 잡아서 요양원 집어 넣어줌 ㅋㅋㅋ

멀쩡히 돌아다니는 에이즈 똥꼬충도 많은데 그건 컨트롤 가능한 새끼들 이야기고 너 같이 현실도피하는 애들한테는 그런거 없다

너 가족이랑 주변인물 에이즈 감염되는건 막아야 되거든 ㅋㅋㅋ

**Comment by cryptozeny** [comment]
이메일스팸 ㅁㅊ 고만좀보내 ㅋㅋ

**Comment by cryptozeny** [comment]
spam

**Comment by cryptozeny** [comment]
자꾸 스팸보내면 업무방해로 신고한다
