### ISSUE TITLE
너 법이랑 친구냐?

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#15]
법은 너 친구로 안봄

그냥 움직이는 재앙 질병 덩어리로 보지 ㅋㅋㅋㅋ

너 같은 놈은 에이즈 전문 요양병원에 구속시켜도 된다고 법에 명시되어 있다

그냥 에이즈 병원으로 꺼지고 거기 화장실에서 게이 새끼들한테 후장이나 대주면서 살다 에이즈로 뒤지는게 앞으로 니 미래다 ㅋㅋㅋㅋ

**Comment by streetcrypto7** [comment]
느가 에이즈 신고 안하고 돌아다니는게 중대한 법 위반이자 보건소 업무 방해다 이 에이즈충 새끼야

**Comment by cryptozeny** [comment]
spam
