### ISSUE TITLE
Why closing issue?

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#2]
Are you afraid?

**Comment by cryptozeny** [comment]
박제했다 ㅅㄱ

**Comment by streetcrypto7** [comment]
Keep going your illegal speech

**Comment by cryptozeny** [comment]
경찰이 그 이슈를 좋아할것 같다

**Comment by streetcrypto7** [comment]
경찰이 니 친구냐 왜 자꾸 경찰 사칭하냐

**Comment by streetcrypto7** [comment]
공무원 사칭까지 하네 ㅋㅋㅋㅋ

**Comment by cryptozeny** [comment]
저기 락걸린 이슈 너가 지울수있냐? 좀 지워볼래 되나안되나

**Comment by streetcrypto7** [comment]
Impersonation - You may not seek to mislead others as to your identity by copying another person's avatar, posting content under their email address, using a similar username or otherwise posing as someone else. Impersonation is a form of harassment.

Impersonating police is a direct violation of the rule

**Comment by cryptozeny** [comment]
뭐 어자피 신고해서 저거 없어도 경찰은 이미 알고있으니 무관하다

**Comment by streetcrypto7** [comment]
Don't impersonate local police @cryptozeny

**Comment by cryptozeny** [comment]
내가 경찰이 아니고, 내가 경찰한테 너의 사기행각을 모두 신고했다고. 나는 경찰이 아님

**Comment by streetcrypto7** [comment]
How? Did you turn yourself in for sharing child abuse contents?

**Comment by cryptozeny** [comment]
경찰에 신고하는거 별로 어렵지않아

**Comment by streetcrypto7** [comment]
Yeah, you should turn yourself in before being caught.

**Comment by cryptozeny** [comment]
고생했고 남은 인생을 즐기기 바람 ㅅㄱ

**Comment by cryptozeny** [comment]
아참 대포폰 쓰는것도 함께 신고했거든? 걸리기전에 버리던가 해라 ㅋㅋ
