### ISSUE TITLE
야 앞으로 디시 할거냐

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#24]
ㅇㅇ? 너 똥꼬 창남인거 이제 애들 다 알잖아

**Comment by cryptozeny** [comment]
꺼져 사기꾼아

**Comment by streetcrypto7** [comment]
무지개 반사 ㅋㅋㅋㅋ

**Comment by streetcrypto7** [comment]
왜 내가 너한테 사기쳤다는 식으로 글 올리냐 애미터진 스캐머 새끼야

**Comment by cryptozeny** [comment]
사기꾼 맞잖아 이미 신고했다고 수고해라 연락하지말고

**Comment by streetcrypto7** [comment]
너도 사기로 신고했다 슈가스캠 ㅋㅋㅋㅋ

**Comment by streetcrypto7** [comment]
지 스캠코인 팔아먹느라고 주작질하는 새끼 ㅋㅋㅋ

**Comment by cryptozeny** [comment]
내가 무슨 스캠을 했다고?

**Comment by streetcrypto7** [comment]
에이 후장충 새끼야 부끄러운줄 알면 갖고 있는 아이디 탈퇴하고 꺼져라 나처럼 딴 아이디로 바꾸고 굴복해라 그럼 너 무시할게

**Comment by streetcrypto7** [comment]
너 그동안 했던거 비트제니 슈가체인 다 스캠이지 ㅉㅉ

**Comment by streetcrypto7** [comment]
슈가체인 팁봇 먹튀범인이 너냐?

**Comment by cryptozeny** [comment]
너 정신이 좀 이상한것 같은데 병원가봐라

**Comment by streetcrypto7** [comment]
그거 너 자신한테 하는 말이냐 ㅉㅉ 너는 정신병원도 가고 성병검사나 해라 더러운 똥꼬충 창놈 새끼

**Comment by streetcrypto7** [comment]
너네 부모님은 너 후장 대주고 다니는거 아냐?

**Comment by streetcrypto7** [comment]
![1573256566](https://user-images.githubusercontent.com/52137633/68522841-8fbc1d00-02f3-11ea-8397-36897fd7a5ef.png)

이거 너가 전에 올린거 맞냐?

**Comment by cryptozeny** [comment]
왜이렇게 에이즈에 집착하냐 너가 환자같은데?

**Comment by streetcrypto7** [comment]
오늘 찾아보니까 지운거 같더라?

**Comment by cryptozeny** [comment]
너가 합성한거잖아 ㅋㅋ

**Comment by streetcrypto7** [comment]
이 새끼 남한테 뒤집어 씌우기 장인이노 상식적으로 너 같이 후장 대주고 다니는 새끼 있으면 에이즈 의심하지 ㅋㅋㅋ

**Comment by streetcrypto7** [comment]
너가 전에 똥꼬 팔고 다닌것도 내가 주작한거냐?

**Comment by cryptozeny** [comment]
주작 수고해라 사과문쓸거아니면 그만연락해
