### ISSUE TITLE
성매매특별법 위반 성매매알선 행위로 경찰에 신고했다

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#27]
![캡처](https://user-images.githubusercontent.com/52137633/68523422-5cca5700-02fc-11ea-96da-a8885866f692.PNG)

진짜로 신고했다

포상금 개꿀 ㅋㅋㅋ

넌 깜빵이다 창놈 새끼야

깜빵에서 너 닮은 변태 죄수 아저씨들한테 박히기 바란다

영치금으로 여장이나 해라 ㅋㅋㅋ

**Comment by streetcrypto7** [comment]
![1573217850](https://user-images.githubusercontent.com/52137633/68523448-af0b7800-02fc-11ea-8952-5df0b4fc0385.png)

이거 다른 관점으로 보면 알선 아니냐 넌 여자는 아니니까 알선으로 잡으면 됨 ㅋㅋㅋ

**Comment by cryptozeny** [comment]
요샌 포샵도 신고받아주나보네 ㅅㄱ
