### ISSUE TITLE
신고했다

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#3]
이슈 닫아도 못 고침

**Comment by streetcrypto7** [comment]
https://cyberbureau.police.go.kr/index.do ( 여기도 신고 넣음 모욕죄 등등 )

**Comment by streetcrypto7** [comment]
너가 과거에 뭘 했건 내 알바 아닌데, 너 수준을 나한테 드러낼 필요는 없다.

**Comment by streetcrypto7** [comment]
He uploaded child abusive contents, doxxing, harassment, and etc. so I sued him. thanks.

**Comment by cryptozeny** [comment]
대포폰은 형량이 작아서 뭐 별 영향은 없을거다

**Comment by cryptozeny** [comment]
수고하고 다시는 보지말자

**Comment by streetcrypto7** [comment]
Why? I would like to see you in the court.

**Comment by streetcrypto7** [comment]
For doing illegal things of course, and I will know who you are.

**Comment by cryptozeny** [comment]
너가 하는일 다 엎어져서 어떡하냐 그러니까 왜 건들고 그래 목욕재개하고 앞으로는 그러지말고

**Comment by cryptozeny** [comment]
야 근데 cpuchain 나 왜 차단했냐? 너가 뭐하는지 알아야 도움이되는데

**Comment by cryptozeny** [comment]
디코는 재수없어서 안갈꺼지만 트위터 차단은 풀어도되잖아

**Comment by streetcrypto7** [comment]
Please ask @minkcrypto, I don't own that account.

**Comment by cryptozeny** [comment]
뭐야 같은놈 아니었어?

**Comment by cryptozeny** [comment]
그놈한테 나 차단좀 풀어달라고해라

**Comment by cryptozeny** [comment]
트위터

**Comment by cryptozeny** [comment]
야 @volbil도 차단당했대 대체 왜그러냐?

**Comment by streetcrypto7** [comment]
전에 뭐 개랑 싸웠다고 그러지 않았나 아무튼 ㅅㄱ 이메일 도배 자제해라

**Comment by cryptozeny** [comment]
volbil이 기껏 힘들게 만든거 훔쳐가놓고 차단하는게 사람이할짓인가?

**Comment by cryptozeny** [comment]
아니 스패밍은 지가해놓고 성내네

**Comment by streetcrypto7** [comment]
트위터는 내가 권한이 없고, 디코는 내가 슈가체인에 있는 사람들 대조해서 내 권한으로 다 밴했다, 깽판 치지 마라

**Comment by streetcrypto7** [comment]
텔레도 있긴 한데 거긴 사람이 워낙 없어서 모르겠다

**Comment by cryptozeny** [comment]
밍크크립토 그놈은 대체 누구야

**Comment by cryptozeny** [comment]
전에 니가말한 보스가 그놈이냐?

**Comment by streetcrypto7** [comment]
보면 모르냐 말레이시안이잖아 나도 개인적인건 몰라 어쩌다 슈가 밴 당하고 벨코인 방에서 스카웃된거임

**Comment by cryptozeny** [comment]
벨코인방에서 그놈이 널스카웃했다고?

**Comment by cryptozeny** [comment]
상장비용도 다 그놈이 낸거야?

**Comment by streetcrypto7** [comment]
자기가 벨코인이랑 Yenten 작업하는데 같이 하자고 하더라고 dnsseed 랑 nomp 도와주고 최근에 그 러시안 애가 한거 베끼고 있지 내가

**Comment by streetcrypto7** [comment]
내가 돈이 어디 있겠냐?

**Comment by cryptozeny** [comment]
거래소는 너가만든거 아니고? 제임스안이 너잖아

**Comment by cryptozeny** [comment]
거래소는 너가한거아니야?

**Comment by streetcrypto7** [comment]
ㅇㅇ 그건 나지, 내 텔레 아이디가 그거임

**Comment by cryptozeny** [comment]
그놈은 딱히 하는일 없어보이던데 너혼자 다하는거 아니었어?

**Comment by streetcrypto7** [comment]
난 텔발 관리자인데 그냥 매니징만 도와주고 있음

**Comment by cryptozeny** [comment]
뭐야 지금껏 둘다 너인줄알았는데

**Comment by cryptozeny** [comment]
이번에도 돈먹고 튈꺼냐?

**Comment by streetcrypto7** [comment]
더 알아서 뭐하냐 됬다 꺼저라 경찰서에서 보자 명예훼손으로, 피고발인 해서 너 이름이랑 기타 등등 알 수 있다 합의할때나 보자

**Comment by cryptozeny** [comment]
ㅇㅋ 뭐 어자피 볼거 나중에봐

**Comment by streetcrypto7** [comment]
내가 혼자서 일하고 있다고 생각하면 오산이야 참고로, 너보다 우리 자금이 더 많아

**Comment by streetcrypto7** [comment]
너 마켓 메이킹도 못하잖아 슈가체인 몇개 가지고 있냐 만개? 십만개?

**Comment by cryptozeny** [comment]
자금이 얼마나되냐? 자전거래도 돌리는것 같던데

**Comment by cryptozeny** [comment]
슈가체인 걍 재미로 하는거라 그냥 명예직이다.

**Comment by streetcrypto7** [comment]
당연히 돌리지, 투자 받을거만 30억이고 그 전에 선납으로 1억 받았다

**Comment by streetcrypto7** [comment]
딴 코인도 만들꺼야, 저기 내가 전에 한거 포크 뜬거 봤지?

**Comment by cryptozeny** [comment]
전에 먹고튄건 갚았냐? 너찾던대ㅔ 누가

**Comment by streetcrypto7** [comment]
IEO 해서 돈 더 모을꺼다

**Comment by streetcrypto7** [comment]
누가 찾냐 보나마나 뻔하겠지만

**Comment by cryptozeny** [comment]
슈가 베낄라는건 진작에 알고 너한테 안줬지. 뭐 지금은 베끼던지말던지 ㅋㅋ 함정이 하나 있으니 조심하고 ㅋ

**Comment by streetcrypto7** [comment]
ㅇㅇ 함정 다 찾았다

**Comment by cryptozeny** [comment]
ㅇㅋ 이름은 뭘로할꺼냐? 사카린 어때?

**Comment by streetcrypto7** [comment]
난 GetPoWhash 만 있으면 됨, 좀 있으면 체인 새로 만들꺼다 1월쯤에

**Comment by cryptozeny** [comment]
거기에 함정이 하나있다 ㅋㅋ 경찰서에서 만나면 알려줄게 ㅋ

**Comment by streetcrypto7** [comment]
이름 존나 간지 나는거 있지, IEO로 내가 얼마 땡길꺼라고 생각하냐?

**Comment by streetcrypto7** [comment]
너네 집은 내가 그냥 살 수 있다 너 잡아넣는데 김앤장 붙일 수 있음, 변호사는 있냐?

**Comment by streetcrypto7** [comment]
준호 무슨 법무법인 잘 알잖아 개랑 해?

**Comment by cryptozeny** [comment]
응 판사 한명 알아 ㅋ

**Comment by cryptozeny** [comment]
준호는 이일과 무관하다 걔 알바하느라 바빠

**Comment by streetcrypto7** [comment]
야 너 전에 호모 아저씨들한테 그거 판거 사실이냐?

**Comment by streetcrypto7** [comment]
에이즈 검사는 했냐?

**Comment by cryptozeny** [comment]
에이즈검사는 너가 달심네 보건소가서 한거잖아 ㅁㅊ

**Comment by streetcrypto7** [comment]
진짜 너 막나가는거 알고 있었는데 자제해라... 성병 걸리면 답 없다

**Comment by streetcrypto7** [comment]
너는 안했잖아 이 에이즈 보균자야

**Comment by cryptozeny** [comment]
조언 고맙다 ㅋ

**Comment by cryptozeny** [comment]
야 하나만 묻자 cpufinex 이거 스캠이냐?

**Comment by streetcrypto7** [comment]
야 넌 의자 않을떄마다 똥 새냐? 내가 게이가 아니라서 모르겠다

**Comment by streetcrypto7** [comment]
너가 바텀임? 아 바텀알바인가 그거지 너 자주 하는거?

**Comment by streetcrypto7** [comment]
존조가 알려줬거든?

**Comment by cryptozeny** [comment]
상장비 얼마받냐 공짜로 상장해주면 경찰신고 취소할께 ㅋ

**Comment by streetcrypto7** [comment]
아니 제발 부탁인데 랜선으로 에이즈 옭기고 다니지 마라

**Comment by cryptozeny** [comment]
상장비 얼마냐고 ㅋㅋ 공짜상장 가능?

**Comment by cryptozeny** [comment]
요새 볼륨이 안나와서 고민이다

**Comment by streetcrypto7** [comment]
ㄴㄴ 저기 달심한테 앙망하고 에이즈 검사나 받아라 진지한 조언이다 진짜 여친이나 가족한테 성병 옭기고 다니지 마

**Comment by cryptozeny** [comment]
나는 2d가 더좋다 ㅋㅋ 그런거 노관신

**Comment by streetcrypto7** [comment]
그리고 바텀알바 자제해라 너 같은 애들 때문에 국민보험 기금이 고갈나고 있다....

**Comment by streetcrypto7** [comment]
고작 몇푼 번다고 자기 똥구멍 팔아서 좆같은 병이나 달고 사냐...

**Comment by cryptozeny** [comment]
야 뭐 그렇다고 생계가 어렵지는 않아 ㅋㅋ 강남에 집도있어 왜이래 ㅋ

**Comment by cryptozeny** [comment]
야 너네 거래소 스캠이냐고 궁금하다 그것이

**Comment by streetcrypto7** [comment]
뭐 그렇다고? 하 씨발 제발 정신차려라... 에이즈 검사 받고 양성이면 빨리 약 먹어 너 애이즈로 뒤지면 그거 채굴한 애들 어카냐

**Comment by cryptozeny** [comment]
뭐야 너 에이즈걸렸냐? 왜 타령이야 ㅋ

**Comment by cryptozeny** [comment]
어자피 해시도 안나오고 채굴자도 아직 얼마안됨ㅋ

**Comment by cryptozeny** [comment]
문의는 자주온다 채굴세력한테

**Comment by streetcrypto7** [comment]
야 내 모니터가 오염되고 있어서 이슈 닫는다 
https://map.naver.com/v5/search/%EA%B0%95%EB%82%A8%EB%B3%B4%EA%B1%B4%EC%86%8C?c=14140994.2862664,4513331.8124654,15,0,0,0,dh

빨리 여기 가서 검사 받아라 성병검사 익명에 무료니까 걱정 안해도 됨

**Comment by cryptozeny** [comment]
너가 저번에 디코 날려서 다떠났잖아! 이것때문에 경찰에 신고했다

**Comment by cryptozeny** [comment]
너가 앞으로 다시는 슈가체인에 얼씬대지 않겠다고 약속하면 경찰신고 취소한다. 포크하던말던 내알바아니고

**Comment by streetcrypto7** [comment]
니 디코방을 날린 디코 본사에 소송을 걸어야지 왜 애먼 나를 신고하고 그러냐 무고죄로 잡혀가고 싶나 진짜

**Comment by cryptozeny** [comment]
슈가디코 누가신고한거야?

**Comment by streetcrypto7** [comment]
뭔 개소리야 제발 남의 신상 doxxing 하는거나 그만둬라

**Comment by streetcrypto7** [comment]
그리고 경찰에 신고한건 내 알바 아닌데 에이즈 검사나 받아라 잠만 있어봐

**Comment by cryptozeny** [comment]
너가한거아니었어? 슈가디코 날린걸로 경찰에 신고한겅 아니지 당연히. 니 과거 스캠기록을 신고했고

**Comment by cryptozeny** [comment]
플래티넘 이더 대포폰 세개 신고했어

**Comment by streetcrypto7** [comment]
http://www.kaids.or.kr/?c=2/37/42/72

이거나 봐라

제5조(의사 또는 의료기관 등의 신고) ① 감염인을 진단하거나 감염인의 사체를 검안한 의사 또는 의료기관은 보건복지부령으로 정하는 바에 따라 즉시 진단·검안 사실을 관할 보건소장에게 신고하고, 감염인과 그 배우자(사실혼 관계에 있는 사람을 포함한다. 이하 같다) 및 성 접촉자에게 후천성면역결핍증의 전파 방지에 필요한 사항을 알리고 이를 준수하도록 지도하여야 한다. 이 경우 가능하면 감염인의 의사(意思)를 참고하여야 한다.

② 학술연구 또는 제9조에 따른 혈액 및 혈액제제(血液製劑)에 대한 검사에 의하여 감염인을 발견한 사람이나 해당 연구 또는 검사를 한 기관의 장은 보건복지부령으로 정하는 바에 따라 즉시 보건복지부장관에게 신고하여야 한다.

③ 감염인이 사망한 경우 이를 처리한 의사 또는 의료기관은 보건복지부령으로 정하는 바에 따라 즉시 관할 보건소장에게 신고하여야 한다.

④ 제1항 및 제3항에 따라 신고를 받은 보건소장은 특별자치시장·특별자치도지사·시장·군수 또는 구청장(자치구의 구청장을 말한다. 이하 같다)에게 이를 보고하여야 하고, 보고를 받은 특별자치시장·특별자치도지사는 보건복지부장관에게, 시장·군수·구청장은 특별시장·광역시장 또는 도지사를 거쳐 보건복지부장관에게 이를 보고하여야 한다.

[전문개정 2013.4.5.]

제6조 삭제  <2008.3.21.>

제7조(비밀 누설 금지) 다음 각 호의 어느 하나에 해당하는 사람은 이 법 또는 이 법에 따른 명령이나 다른 법령에서 정하고 있는 경우 또는 본인의 동의가 있는 경우를 제외하고는 재직 중에는 물론 퇴직 후에도 감염인에 대하여 업무상 알게 된 비밀을 누설하여서는 아니 된다.

1. 국가 또는 지방자치단체에서 후천성면역결핍증의 예방·관리와 감염인의 보호·지원에 관한 사무에 종사하는 사람

2. 감염인의 진단·검안·진료 및 간호에 참여한 사람

3. 감염인에 관한 기록을 유지·관리하는 사람


야 나라에서 너 같이 자기 행동으로 병신같은 병 걸린 애들 세금으로 지원하니까, 법이나 지키고 너 이사 갈떄 뒤질떄 보건소에 신고하는거 잊지 말아라

**Comment by cryptozeny** [comment]
너가 슈가에 얼씬대지 않겠다고 서약하면 경찰신고 취소할게 ㄹㅇ임

**Comment by streetcrypto7** [comment]
그리고 니 여친이랑 결혼하거나 그거할떄 너 에이즈 걸린거 밝혀라 안 밝히면 위법임

**Comment by streetcrypto7** [comment]
야 제발 부탁인데 나중에 김정은이 한국 오면 그떄 정은이한테 니 피나 뿜어줘라 생화학 공격 개꿀임 위인전에 실릴수 있다

**Comment by cryptozeny** [comment]
야 에이즈는 걱정말고 서약할래말래? 아직 고소취하할수있을지도모름

**Comment by cryptozeny** [comment]
너찾는사람 있던데 잘생각해 ㅋ

**Comment by streetcrypto7** [comment]
![](https://img.extmovie.com/files/attach/images/135/867/946/013/0399ae8c306312d532ecf744558392b1.jpg)

**Comment by cryptozeny** [comment]
너가 손해볼게없다

**Comment by cryptozeny** [comment]
니가 슈가 괴롭혀서 얻는이득이 뭐냐? 경찰서행 ㅋㅋ

**Comment by cryptozeny** [comment]
서약서 쓰고 pgp 서명해서 이메일로 보내라 이 아이디로 그럼 고발취소한다 국문영문 둘다써라 한국변호사한테 보낼거니

**Comment by cryptozeny** [comment]
야 그리고 사죄의 의미로 너코인좀 나한테 보내. 그럼 긍정적으로 생각해보마
cpuchain address
```
CUw9rqLSppfvWRxPaRwf88EPnwrPsDBE6o
```

**Comment by cryptozeny** [comment]
야 글고 이딴거좀 고쳐
```
cpuchain-0.16.3$ ./bin/cpuchain-qt 
libpng warning: iCCP: known incorrect sRGB profile
```
그지같이 만들었냐?

**Comment by cryptozeny** [comment]
잘생각해보고 PGP서명해서 사과문 국문/영문 보내라.

```md
Subjuct: I will stop attacking Sugarchain and cryptozeny anymore
Contents:
I (streetcrypto7) swear that ...
``` 

여기에 남겨도 되고 아무데나 남겨

**Comment by streetcrypto7** [comment]
진짜 머리 잘 쓴다... 하긴 똥꼬 팔려고 해도 부단한 노력이 필요하지 않냐? 여장도 하고 가슴도 달고 여성 호르몬도 주사하고 마약도 하고 그러지? 에휴 세상이 말세다...

**Comment by cryptozeny** [comment]
경찰서 가는것보단 낫잖아? 싫음말고
