### ISSUE TITLE
신고했다

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#4]
![sue](https://user-images.githubusercontent.com/52137633/68281827-d1fb1980-00bb-11ea-911e-6c9d3b926553.PNG)

이슈 닫고 튀기에는 너무 늦었다

**Comment by streetcrypto7** [comment]
I've reported @cryptozeny's illegal activity, he will be arrested soon.

**Comment by cryptozeny** [comment]
너가 더 먼저 잡힌다니까 그러네 스팸좀 그만해 바빠
