### ISSUE TITLE
I know you want to remain anonymous

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#5]
and keep doxxing people, threating others, but.

I've reported and you will be soon arrested, I will know who you are @cryptozeny, I think it is not so far.

Please give your sugarchain dev position to others before you go into jail.

**Comment by cryptozeny** [comment]
내걱정 말라니깐 그러네

**Comment by cryptozeny** [comment]
아니면 지금 잠깐볼래? 학교앞에서

**Comment by streetcrypto7** [comment]
디코 차단 풀어놔라 숙제 하나 하고 너 잡으러 간다

**Comment by cryptozeny** [comment]
그냥 여기서 해 괜찮아 ㅋ

**Comment by streetcrypto7** [comment]
streetcrypto7 블락 풀어라 시간 알려준다

**Comment by cryptozeny** [comment]
학교앞에서 만나지않을래?

**Comment by streetcrypto7** [comment]
그리고 지금 나가야 되서 깃헙 못봐 디코 와라

**Comment by cryptozeny** [comment]
여기서 하라니까 디코는 못믿겠어 ㅋ

**Comment by cryptozeny** [comment]
디코 불매운동중이거든 됐고 여기서해 ㅋ

**Comment by streetcrypto7** [comment]
ㅇㅇ 디코는 신고 안할테니까 해라 못 입었다 나간다

**Comment by cryptozeny** [comment]
야 너찾는 사람들 지금 많은거 알지? 근데 어쩌냐

**Comment by cryptozeny** [comment]
방금 검색해보니 좀 더 많아진것같은데...

**Comment by cryptozeny** [comment]
퀴즈: 내가 지금 어디있게?

**Comment by streetcrypto7** [comment]
헛소리 할꺼면 이거 닫는다, 그리고 너가 신고 못하는거 알고 있음. 고발인 신원 드러나는거 알지?

**Comment by streetcrypto7** [comment]
디코 와라 거기서 보자

**Comment by streetcrypto7** [comment]
참고로 내 신상은 너가 아니까 난 신고해도 상관 없음, 난 너가 알고 싶을 뿐이야.

**Comment by streetcrypto7** [comment]
답 없으면 이거 걍 닫는다

**Comment by cryptozeny** [comment]
나는 너 신상 전혀 모르는데?

**Comment by cryptozeny** [comment]
준호이름으로 고발했어 ㅋㅋ 나아님ㅋ

**Comment by streetcrypto7** [comment]
ㅇㅇ 난 너 고발함

**Comment by streetcrypto7** [comment]
준호가 고발한건 개랑 나 사이의 문제지 님이랑 무슨 상관이냐, 난 개 볼 필요성이 없는데 님은 있다, 내 개인적 호기심임.

**Comment by streetcrypto7** [comment]
그리고 개는 왜 날 고발하냐 ㅋㅋㅋ 무고죄라는걸 모르나 보지?

**Comment by cryptozeny** [comment]
지금 볼까 그럼?

**Comment by streetcrypto7** [comment]
형법 제156조(무고) 타인으로 하여금 형사처분 또는 징계처분을 받게 할 목적으로 공무소 또는 공무원에 대하여 허위의 사실을 신고한 자는 10년 이하의 징역 또는 1천500만원 이하의 벌금에 처한다.

이거 쌔네 ㅋㅋㅋ 너는 지난번에 내 실명 까고 욕한거 있잖아, 님은 특정이 됨

**Comment by streetcrypto7** [comment]
준호도 고발하라 그래라 , 징역 10년이다 스물 몇이였던걸로 알고 있는데 30대로 타임워프 시켜주마

**Comment by streetcrypto7** [comment]
님도 깜빵가고 싶어?

**Comment by cryptozeny** [comment]
저번에 너가 나 신고한거 경찰에 물어봤는데 그런거 접수안됐다더라 경찰바빠

**Comment by streetcrypto7** [comment]
님은 지난번에 디시에서 나 욕한걸로 다시 신고 넣고 ( 님 고닉은 아이피 특정이 되니까 ) , 준호는 나한테 무슨죄로 고발 오면 무고로 ㅋㅋㅋㅋ

님도 나 고발해라, 법정까지 가서 무고죄로 한번 가즈아아

**Comment by cryptozeny** [comment]
준호는 뻥이고 내가 너 고발한것 맞다. 나중에 내이름 볼거야 수고해

**Comment by streetcrypto7** [comment]
오 배짱 개쌔네 ㅋㅋㅋ 뭘로 했냐?

**Comment by cryptozeny** [comment]
몇년뒤에 나와서 맥주나 한잔 사줄게

**Comment by streetcrypto7** [comment]
마 자신 있으면 들어와라

**Comment by cryptozeny** [comment]
어딜들어와 난 디코가 싫다

**Comment by streetcrypto7** [comment]
https://i.ytimg.com/vi/tVKytsp-22g/maxresdefault.jpg

**Comment by cryptozeny** [comment]
이 수상한 링크는 뭐야

**Comment by cryptozeny** [comment]
경찰서에서 볼껀대 뭐하러보냐 걍 나중에 보자 ㅅㄱ 바쁘다

**Comment by streetcrypto7** [comment]
![images](https://user-images.githubusercontent.com/52137633/68285092-fa861200-00c1-11ea-8897-e4921cc12f24.jpg)

야 나 운동 많이 했냐?

**Comment by cryptozeny** [comment]
화장실이 구리다 리모델링해라

**Comment by cryptozeny** [comment]
쌍팔년도 아파트에사냐?

**Comment by streetcrypto7** [comment]
야

제47조(벌칙) ① 삭제② 자기 또는 타인에게 이익을 주거나 타인에게 손해를 가할 목적으로 전기통신설비에 의하여 공연히 허위의 통신을 한 자는 3년이하의 징역 또는 3천만원이하의 벌금에 처한다.③ 제2항의 경우에 그 허위의 통신이 전신환에 관한 것인 때에는 5년 이하의 징역 또는 5천만원 이하의 벌금에 처한다.④ 전기통신업무에 종사하는 사람이 제3항의 행위를 한 때에는 10년 이하의 징역 또는 1억원 이하의 벌금에 처하고, 제2항의 행위를 한 때에는 5년 이하의 징역 또는 5천만원 이하의 벌금에 처한다.

너 고발 안했으면서 했다고 하면 가짜뉴스 허위사실 유포인거 알지?

**Comment by cryptozeny** [comment]
알지

**Comment by streetcrypto7** [comment]
그리고 우리집 왜 비하하냐 신고한다

**Comment by cryptozeny** [comment]
집 구리다고 해서 미안하다

**Comment by volbil** [comment]
For the fuck sake, don't you have other things to work on 🤔 ?

**Comment by cryptozeny** [comment]
lol no idea

**Comment by streetcrypto7** [comment]
@volbil Hello Dmitry

**Comment by volbil** [comment]
Hi there @streetcrypto7

**Comment by cryptozeny** [comment]
lets talk about the future of our crypto currency plz

**Comment by streetcrypto7** [comment]
![](https://avatars2.githubusercontent.com/u/8951070?s=460&v=4) nice place you have, where is it? @volbil

**Comment by cryptozeny** [comment]
hey its doxxing lol

**Comment by streetcrypto7** [comment]
@cryptozeny It is his github profile https://github.com/volbil

**Comment by streetcrypto7** [comment]
야 나 보자매 안보냐?

**Comment by volbil** [comment]
@streetcrypto7 https://g.page/murchison-falls-national-park?share
Nice place, you can visit it some day

**Comment by streetcrypto7** [comment]
쫄려서 고발도 못하고 디코도 못 하고 나도 못 보고 쫄려서 어떻게 살래

**Comment by cryptozeny** [comment]
hey doxxer police will like you 🤣

**Comment by cryptozeny** [comment]
korean police is very gentle rather than trump wrold lol

**Comment by streetcrypto7** [comment]
@cryptozeny Hey, I would like to play boxing with you

https://www.youtube.com/watch?v=AebQIy5UNng

**Comment by cryptozeny** [comment]
yeah me too but for now i am busy

**Comment by cryptozeny** [comment]
we will meet soon in the 👮 station

**Comment by cryptozeny** [comment]
take care then

**Comment by streetcrypto7** [comment]
If I do some Physiotherapy to you by shocking your head, your impolite attitude will be fixed, I will do the therapy for free lol.

**Comment by cryptozeny** [comment]
ok my friend good bye! 😋
