### ISSUE TITLE
크립토제니 미래

### ISSUE THREAD

**Issue by streetcrypto7** [cryptozeny/difficulty#9]
![](https://i.ytimg.com/vi/vvMll_NcwcE/hqdefault.jpg)

아 미래가 아니라 본인인거 같은데

빨리 컴퓨터 끄고 병원이나 가서 똥꼬충들이랑 같이 격리병동에서 요양이나 해라

**Comment by cryptozeny** [comment]
아침부터 ㅈㄹ이냐 사과문이나 빨리써서보내
